### PR TITLE
Fixing #2906: improve draining

### PR DESCRIPTION
**Pull request by zizhong**
1. Adding `traffic server drain` subcommand
2. Adding default option, --no-new-connection option and --undo option

TODO:
1. implement `is_server_idle_from_new_connection()`
2. update docs
3. adding tests

### CODE REVIEW

**Comment by zizhong** [comment]
@maskit please take a look when you have time.

**Comment by maskit** [comment]
@zizhong Thanks for this improvements.

I can take a look at the change if you want, but I'm not so familiar with this area actually. So it would be better to ask some traffic_manager / traffic_ctl experts and other real users (e.g. ops teams).

Also, as you can see, the diff is incomplete because our changes are separated. To get better feedback, we should probably create a new PR for the real master branch with the both changes. Probably I wouldn't be able to take much time to improve draining feature for a while, please feel free to take my change and send the PR if you want.

A couple of comments for now.
- What would be the difference between `--no-new-connection` and `proxy.config.restart.stop_listening`?
- `start` and `stop` sounds like a pair of subcommands.  It might be great if we could find something for `--undo`.

**Comment by zizhong** [comment]
Thanks, @maskit for the reply. Much appreciated.
Sure, I will combine both PRs and submit it to upstream.

To answer your comments, `--no-new-connection` is to start draining the keepalive connection after no new connection is coming in.
About `start`, `stop` and `--undo`, I'll consider them. Maybe there is a better way to organize them.

**Comment by zizhong** [comment]
The new PR is opened. https://github.com/apache/trafficserver/pull/2962
Closing this.

**Pull request closed without merging**
